# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices."DECRYPTED_ROOT".device =
    "/dev/disk/by-uuid/5e23b356-3494-4640-8f20-6aad670ee77c";
  boot.initrd.luks.devices."DECRYPTED_DATA" = {
    device = "/dev/disk/by-uuid/793e74af-381e-434c-b2b6-01206cf6edfd";
    keyFile = "/root/password:/dev/mapper/DECRYPTED_ROOT";
  };

  fileSystems."/" = {
    device = "/dev/mapper/DECRYPTED_ROOT";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "ssd"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/DECRYPTED_ROOT";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "ssd"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/DECRYPTED_DATA";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "nossd"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/535d8814-8541-4ac2-9cfb-ed0bf3852b0c";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/93EE-5783";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };
  fileSystems."/etc/nixos" = {
    device = "/mkk/config";
    fsType = "none";
    options = [ "bind" ];
    depends = [ "/" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/9a5795a9-8ddb-4be0-b8f7-e59270ba8db9"; }
  ];
  zramSwap = {
    enable = true;
    memoryPercent = 50;
    priority = 10;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
