# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot.kernelParams = [

  ];

  boot.plymouth = {
      enable = true;
    };
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ 
    "nvidia"
    "nvidia_drm"
    "nvidia_modeset"
    "nvidia_uvm"
  ];
  boot.kernelModules = [
    "kvmfr"
    "kvm-intel"
    "vfio"
    "vfio_iommu_type1"
    "vfio-pci"
  ];
  boot.extraModprobeConfig = ''
    options kvmfr static_size_mb=64
  '';
  boot.extraModulePackages = with config.boot.kernelPackages; [
    kvmfr
  ];

  boot.supportedFilesystems = [
    "ntfs"
    "nfs"
  ];

  services.udev.extraRules = ''
    SUBSYSTEM=="kvmfr", OWNER="root", GROUP="kvm", MODE="0660"
  '';

  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices."DECRYPTED_ROOT".device =
    "/dev/disk/by-uuid/5e23b356-3494-4640-8f20-6aad670ee77c";
  boot.initrd.luks.devices."DECRYPTED_DATA" = {
    device = "/dev/disk/by-uuid/793e74af-381e-434c-b2b6-01206cf6edfd";
    keyFile = "/root/password:/dev/mapper/DECRYPTED_ROOT";
  };

  fileSystems."/" = {
    device = "/dev/mapper/DECRYPTED_ROOT";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "ssd"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/DECRYPTED_ROOT";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "ssd"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/DECRYPTED_DATA";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "nossd"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/mkk/mnt/data" = {
    device = "/dev/mapper/DECRYPTED_DATA";
    fsType = "btrfs";
    options = [
      "subvol=@data"
      "nossd"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/535d8814-8541-4ac2-9cfb-ed0bf3852b0c";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/93EE-5783";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };
  fileSystems."/etc/nixos" = {
    device = "/mkk/config";
    fsType = "none";
    options = [ "bind" ];
    depends = [ "/" ];
  };

  fileSystems."/home/materus/.cache/nvidia" = {
    device = "/mkk/ssd_data/nvidia_cache/default";
    fsType = "none";
    options = [ "bind" ];
    depends = [ "/" ];
  };

  fileSystems."/home/materus/.cache/shader" = {
    device = "/mkk/ssd_data/nvidia_cache";
    fsType = "none";
    options = [ "bind" ];
    depends = [ "/" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/9a5795a9-8ddb-4be0-b8f7-e59270ba8db9"; }
  ];
  boot.zswap = {
    enable = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
